import Testing
import Foundation
import AppKit
@testable import Mini_Capsule

@MainActor
@Suite(.tags(.unit))
struct ReadPasteboardSkipTests {
    private func monitor() -> ClipboardMonitor {
        ClipboardMonitor(settings: MockSettingsForSeams(), pasteboard: FakePasteboard())
    }
    private func t(_ raw: String) -> NSPasteboard.PasteboardType { .init(raw) }

    @Test func concealedTypeReturnsNil() {
        let pb = FakePasteboard()
        let types: [NSPasteboard.PasteboardType] = [.string, t("org.nspasteboard.ConcealedType")]
        pb.stubbedStrings[.string] = "secret"
        #expect(monitor().readPasteboard(pb, types: types) == nil)
    }

    @Test func transientTypeReturnsNil() {
        let pb = FakePasteboard()
        let types: [NSPasteboard.PasteboardType] = [.string, t("org.nspasteboard.TransientType")]
        pb.stubbedStrings[.string] = "temp"
        #expect(monitor().readPasteboard(pb, types: types) == nil)
    }

    @Test func autoGeneratedTypeReturnsNil() {
        let pb = FakePasteboard()
        let types: [NSPasteboard.PasteboardType] = [.string, t("org.nspasteboard.AutoGeneratedType")]
        pb.stubbedStrings[.string] = "auto"
        #expect(monitor().readPasteboard(pb, types: types) == nil)
    }

    @Test func noRecognizedTypeReturnsNil() {
        let pb = FakePasteboard()
        let types: [NSPasteboard.PasteboardType] = [t("com.unknown.custom")]
        #expect(monitor().readPasteboard(pb, types: types) == nil)
    }
}
